name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run golangci-lint
        uses: actions-contrib/golangci-lint@v1

